[package]
name = "json-fixer"
version = "0.1.0"
edition = "2024"


[features]
#default = []
#serde = ["dep:serde", "dep:serde_json"]


[dependencies]
serde = { version = "1.0.217", features = ["derive"]} #optional = true 
serde_json = { version = "1.0.135"} #optional = true 
